apiVersion: v1
kind: Namespace
metadata:
  name: watchlist-app
---
# MongoDB Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: watchlist-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: watchlist-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: watchlist-app
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# Auth-Service Deployment (with frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: watchlist-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: dvinzzzz/auth-service:latest
        ports:
        - containerPort: 5000
---
# Auth-Service Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: watchlist-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
# Movie-Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: watchlist-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: dvinzzzz/movie-service:latest
        ports:
        - containerPort: 5001
---
# Movie-Service Service
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: watchlist-app
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
